os: osx
osx_image: xcode11.2
language: node_js
node_js: '12'
script:
  - npm run dist

deploy:
    provider: releases
    skip_cleanup: false
    api_key: $GH_TOKEN
    file_glob: true
    file:
      - "dist/ta3-*-mac.zip"
      - "dist/ta3-setup-*.exe"
    on:
      tags: true